### ISSUE TITLE
Configure Openstack controller

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/dockerbuild#17]
Needed settings for the app container:

1. Keystone URL
2. Tenant (default oscm)
3. Domain (default default)
4. Credentials (oscm, <password>)

**Comment by batikanu** [comment]
configsettings_controller.properties -> 
# Copyright FUJITSU LIMITED 2016
# Asynchronous Provisioning Platform Controller Settings
CONTROLLER_ID=ess.openstack

# General controller settings
BSS_ORGANIZATION_ID=<organizationID>
BSS_USER_ID=<userId>
BSS_USER_KEY=<userKey>
BSS_USER_PWD=_crypt:<password>

# OpenStack controller-specific settings
API_USER_NAME=<userName>
API_USER_PWD=_crypt:<password>
KEYSTONE_API_URL=http://<keystone endpoint>/<version>/auth
TEMPLATE_BASE_URL=http://<app>/docroot/templates/
# Unique Tenant ID (Project ID) in OpenStack
TENANT_ID=<tenantid>
DOMAIN_NAME=<domain>
READY_TIMEOUT=300000

**Comment by batikanu** [comment]
it is implemented already
